theme: jekyll-theme-dinky

# Site wide configuration

title:            Wamwiki
locale:           en_US
url:			 https://wamwiki.github.io/

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Site owner
owner:
  name: Wamwiki
  avatar: biophoto.jpg
  bio: "Wild quantitative genetics"
  email: wambamwiki@gmail.com
  disqus-shortname: wamwiki-github-io.disqus.com
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #number
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: wamwiki
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
