theme: jekyll-theme-dinky

# Site wide configuration

title:            Wamwiki
locale:           en_US
url:			 https://wamwiki.github.io/

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

